### Create a new Patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Consumer",
  "email": "ConsumerTest@mail.com",
  "address": "Kafka street",
  "dateOfBirth": "1995-07-09",
  "registeredDate": "2025-08-07"
}

###